<script>
    jQuery("div#okCambis").fadeIn(300);
</script>
<div id="cont1editar" style="clear:both;padding-top:20px;">
    <div style="float:left;">
        <div style="height: 15px; background: #eeeeee">
            Nombre de Usuario:
        </div>
        <input type="text" id="username" name="username" class="text-input placeholder-input" style="width:225px;" value="<?php echo $this->dades->username;?>" />
    </div>
    <div style="float:left;margin-top:17px;">
        <span class="ejemplo" style="background: #ffffff;margin-left:20px;">
        </span>
    </div>
</div>
<div id="cont1editar" style="clear:both;padding-top:20px;">
    <div style="float:left;">
        <div style="height: 15px; background: #eeeeee">
            Nombre:
        </div>
        <input type="text" id="nombre" class="text-input placeholder-input" style="width:225px;" value="<?php echo $this->dades->nombre?>" />
    </div>
    <div style="float:left;margin-top:17px;">
        <span class="ejemplo" style="background: #ffffff;margin-left:20px;">
        </span>
    </div>
</div>
<div id="cont1editar" style="clear:both;padding-top:20px; float:left;">
    <div>
        <div style="height: 15px; background: #eeeeee">
            Primer Apellido:
        </div>
        <input type="text" id="apellido1" class="text-input placeholder-input" style="width:225px;" value="<?php echo $this->dades->primer_apellido?>" />
    </div>
</div>
<div id="cont1editar" style="float:left;padding-top:20px; padding-left: 40px;">
    <div>
        <div style="height: 15px; background: #eeeeee">
            Segundo Apellido:
        </div>
        <input type="text" id="apellido2" class="text-input placeholder-input" style="width:225px;" value="<?php echo $this->dades->segundo_apellido?>" />
    </div>
</div>
<div id="cont1editar" style="clear:both;padding-top:20px;">
    <div style="float:left;">
        <div style="height: 15px; background: #eeeeee">
            Email:
        </div>
        <input type="text" id="email" class="text-input placeholder-input" style="width:225px;" value="<?php echo $this->dades->email?>" />
    </div>
    <div style="float:left;margin-top:17px;">
        <span class="ejemplo" style="background: #ffffff;margin-left:20px;">
        </span>
    </div>
</div>
