<div class="column-container group">
    <div class="columns group">
        <div class="pre-content">
            <div id="left-column" class="column narrow attached-menu  group">
                 <?php
                //aqui fem un include
                echo $this->render("opcionsperfil.phtml"); ?>
            <div id="titul-categorias" style="margin-top:35px;">
               Gestionar Perfil:
            </div>
             <ul class="sidebar-menu" >
                    <li>
                        <a id="categoria"  href="<?php echo $this->baseUrl();?>/privat/editar">Imagen y Aficiones
                        </a>
                    </li>
                    <li>
                        <a id="categoria" href="<?php echo $this->baseUrl() ?>/privat/password">Cambiar Contraseña
                        </a>
                    </li>
                    <li>
                        <a id="categoria"  href="<?php echo $this->baseUrl() ?>/privat/datospersonales">Datos Personales
                        </a>
                    </li>
                    <li>
                        <a id="categoria" class="active" href="<?php echo $this->baseUrl() ?>/privat/etiquetas">Gestionar Etiquetas
                        </a>
                    </li>
            </ul>
            </div>
            <div id="main-column" class="column attached-menu group">
                 <div id="titul-categorias" style="padding-left:4px; background:#f2f2f2; border-top:1px solid #e2e2e2; padding:4px 5px 4px 5px;">
                      Gestionar Etiquetas
                   </div>
                 <div style="margin-top:15px;padding-left:5px;"><strong>¿Para que sirven las Etiquetas?</strong></div>
                <div style="clear:both;margin-top:10px; padding-left:5px;">Desde Noticias de Interes podras ver las noticias que contengan alguna de mis etiquetas.</div>
                <div style="clear:both;margin-top:10px; padding-left:5px;">Desde aqui puedes añadir y borrar tus etiquetas.</div>
                <div style="clear:both;margin-top:10px; padding-left:5px;">Las etiquetas puedes añadirlas de una en una o muchas separadas por comas.</div>
                <div id="cont1editar" style="clear:both;padding-top:50px;">
                        <input tabindex="1" type="text" style="margin-left:14%;width: 240px;float:left;" class="text-input placeholder-input" name="etiqueta" id="etiqueta">
                        <span  id="entrar-submit" tabindex="2" class="btn2 btn-special2" style="text-align:center;float:left; height: 16px;">Nueva</span>
                        <div style="float:left;margin-top:15px;">
                            <span class="ejemplo" style="background: #ffffff;margin-left:20px;">
                                Ejemplo: Messi, Libia, PP
                            </span>
                        </div>
                </div>
            </div>
            <div id="right-column" class="column wide group">
                <?php
                //aqui fem un include
                echo $this->render("rightsidebar.phtml");
                ?>
            </div>
        </div>
    </div>
</div>