<div class="column-container group">
    <div class="columns group">
        <div class="pre-content">
            <div id="left-column" class="column narrow attached-menu  group">
                 <?php
                //aqui fem un include
                echo $this->render("opcionsperfil.phtml"); ?>
                <div id="titul-categorias" style="margin-top:35px;">
                   Gestionar Perfil:
                </div>
             <ul class="sidebar-menu" >
                    <li>
                        <a id="categoria"  href="<?php echo $this->baseUrl();?>/privat/editar">Imagen y Aficiones
                        </a>
                    </li>
                    <li>
                        <a id="categoria" class="active" href="<?php echo $this->baseUrl() ?>/privat/password">Cambiar Contraseña
                        </a>
                    </li>
            </ul>
            </div>
            <div id="main-column" class="column attached-menu group">
                    <div id="titul-categorias" style="padding-left:4px; background:#f2f2f2; border-top:1px solid #e2e2e2; padding:4px 5px 4px 5px;">
                      Cambiar Contraseña
                   </div>
                <div style="margin-top:15px;padding-left:5px;"><strong>¿Quiere cambiar su contraseña?</strong></div>
                <div style="clear:both;margin-top:10px; padding-left:5px;">Tiene que poner su contraseña anterior y su nueva contraseña en los siguientes campos de texto!</div>

                <div id="contenidorPassword" style="margin-top:20px; padding-left: 20px;">
                    <div id="cont1editar" style="clear:both;padding-top:20px;">
                        <div style="float:left;">
                            <div style="height: 15px; background: #eeeeee">
                                Contraseña antigua:
                            </div>
                            <input type="password" id="passOld" class="text-input placeholder-input" style="width:225px;" value=""/>
                        </div>
                        <div style="float:left;margin-top:17px;">
                            <span class="ejemplo" style="background: #ffffff;margin-left:20px;">
                            </span>
                        </div>
                    </div>
                    <div id="cont1editar" style="clear:both;  padding-top:30px;">
                        <div style="float:left;">
                            <div style="height: 15px; background: #eeeeee">
                                Contraseña nueva:
                            </div>
                            <input type="password" id="passNew2" class="text-input placeholder-input" style="width:225px;" value=""/>
                        </div>
                        <div style="float:left;padding-top:20px;">
                            <span class="ejemplo" style="background: #ffffff;margin-left:20px;">
                                Ejemplo contraseña segura: B34xp4Ls
                            </span>
                        </div>
                    </div>
                    <div id="cont1editar" style="clear:both;  padding-top:8px;">
                        <div style="float:left;">
                            <div style="height: 15px; background: #eeeeee">
                                Repetir contraseña nueva:
                            </div>
                            <input type="password" id="passNew1" class="text-input placeholder-input" style="width:225px;" value=""/>
                        </div>
                        <div style="float:left;margin-top:17px;">
                            <span class="ejemplo" style="background: #ffffff;margin-left:20px;">
                            </span>
                        </div>
                    </div>
                    
                </div>
                <div style=" clear:both;float: left;padding-top:22px;padding-left:20px;" id="botoId">
                    <input type="button" id="boto-dades" class="btn btn-primary has-tooltip" value="Cambiar Contraseña"/>
                </div>
            </div>
            <div id="right-column" class="column wide group">
                <?php
                //aqui fem un include
                echo $this->render("rightsidebar.phtml");
                ?>
            </div>
        </div>
    </div>
</div>


<script>
    
    var passwordOld = "<?php echo $this->pass; ?>";

    jQuery("#boto-dades").live("click",function(){
        var error=0;

        if(jQuery("input#passOld").val().length>=6){
            if(/\S/.test(jQuery("input#passOld").val())){
                 var passOld = jQuery("input#passOld").val();
                passOld =jQuery.sha1(passOld);
             }else{
                error = 1;
                jQuery("div#message-dock-password").fadeIn(300);
                setTimeout("tancarFinestreSame()", 5000);
            }
        }else{
            error = 1;
            jQuery("div#message-dock-password").fadeIn(300);
            setTimeout("tancarFinestreSame()", 5000);
        }
        
        if(passOld != passwordOld){
            if(error==0){
                jQuery("div#same-password-dock2").fadeIn(300);
                setTimeout("tancarFinestreSame2()", 5000);
                error=1;
            }
        }
        if(jQuery("input#passNew1").val().length>=6){
            if(/\S/.test(jQuery("input#passNew1").val())){
                passNew1 = jQuery("input#passNew1").val();
            }else{
                if(error==0){
                    jQuery("div#message-dock-password").fadeIn(300);
                    setTimeout("tancarFinestreSame()", 5000);
                    error=1;
                }
            }
        }else{
            if(error==0){
                jQuery("div#message-dock-password").fadeIn(300);
                setTimeout("tancarFinestreSame()", 5000);
                error=1;
            }
        }




        if(jQuery("input#passNew2").val().length>=6){
            if(/\S/.test(jQuery("input#passNew2").val())){
                passNew2 = jQuery("input#passNew2").val();
            }
            else{
                if(error==0){
                    jQuery("div#message-dock-password").fadeIn(300);
                    error=1;
                }
            }
        }else{
            if(error==0){
                jQuery("div#message-dock-password").fadeIn(300);
                error=1;
            }
        }
        if(passNew1 ==  passNew2){
            var passNew = passNew1;
        }else{
            if(error==0){
                jQuery("div#same-password-dock").fadeIn(300);
                error=1;
            }
        }
        id = jQuery("input#id").val();
        
        if(error==0){
            jQuery("div#botoId").html("<img src=\""+baseUrl+"/images/loading.gif\">");
            jQuery.ajax({
                type: "POST",
                url: baseUrl+"/privat/updatepassword",
                async: true,
                data: "&passOld="+passOld+"&passNew="+passNew+"&id="+id,
                
                success: function(data){
                  if(data){
                       jQuery("div#contenidorPassword").html(data);
                       jQuery("div#botoId").html("<input type=\"button\" id=\"boto-dades\" class=\"btn btn-primary has-tooltip\" value=\"Cambiar Contraseña\"/>");

                   }
                }
            })
        }
    });


    jQuery("a.dismiss-dock").live("click",function(){
        jQuery("div#message-dock").fadeOut(50);
    });

     jQuery("a.dismiss").live("click",function(){
        jQuery("div#same-password-dock").fadeOut(50);
    });

    jQuery("a.dismiss_password2").live("click",function(){
        jQuery("div#same-password-dock2").fadeOut(50);
        
    });

    function tancarFinestreSame(){
        jQuery("div#same-password-dock").slideUp(300);
    }

    function tancarFinestreSame2(){
        jQuery("div#same-password-dock2").slideUp(300);
    }

</script>