<script>
    jQuery("div#okCambis").fadeIn(300);
</script>
<div id="cont1editar" style="clear:both;padding-top:20px;">
    <div style="float:left;">
        <div style="height: 15px; background: #eeeeee">
            Contraseña antigua:
        </div>
        <input type="password" id="passOld" class="text-input placeholder-input" style="width:225px;" value=""/>
    </div>
    <div style="float:left;margin-top:17px;">
        <span class="ejemplo" style="background: #ffffff;margin-left:20px;">
        </span>
    </div>
</div>
<div id="cont1editar" style="clear:both;  padding-top:30px;">
    <div style="float:left;">
        <div style="height: 15px; background: #eeeeee">
            Contraseña nueva:
        </div>
        <input type="password" id="passNew2" class="text-input placeholder-input" style="width:225px;" value=""/>
    </div>
    <div style="float:left;padding-top:20px;">
        <span class="ejemplo" style="background: #ffffff;margin-left:20px;">
            Ejemplo contraseña segura: B34xp4Ls
        </span>
    </div>
</div>
<div id="cont1editar" style="clear:both;  padding-top:8px;">
    <div style="float:left;">
        <div style="height: 15px; background: #eeeeee">
            Repetir contraseña nueva:
        </div>
        <input type="password" id="passNew1" class="text-input placeholder-input" style="width:225px;" value=""/>
    </div>
    <div style="float:left;margin-top:17px;">
        <span class="ejemplo" style="background: #ffffff;margin-left:20px;">
        </span>
    </div>
</div>
<script>

    passwordOld = "<?php echo $this->pass; ?>";
</script>