<div class="newsup-btn has-tooltip newsup-dugg">
    <div class="newsup-count-wrapper">
        <span class="newsup-count"><span><?php echo $this->noticia->getNumVots();?></span></span>
    </div>
    <span class="btnpunts-votat btn-special-javotat has-tooltip" rel="<?php echo $this->noticia->getId(); ?>" votat="<?php echo $this->noticia->getId(); ?>" id="puntsNotice">UP&nbsp;<span class="puntuarNew puntuar-new"></span></span>
</div>
