<?php foreach($this->noticiesFinals as $noticia){ ?>
<?php $x=0; ?>
   <?php if($x!=0){ ?>
    <div style="width:100%; height: 1px; background-color: #eeeeee; margin-right: 5px;"></div>
   <?php } ?>
    <?php $x++; ?>
    <div class="story-item-gutters2 group" style="margin-top: 17px; margin-bottom: 14px;">
         <?php if($noticia->getImatge() !=null){ ?>
          <?php  if(!eregi("chrome", $_SERVER['HTTP_USER_AGENT'])){ ?>
            <div class="story-item-media" style="padding-top:10px;">
                <div class="story-item-thumb">
                    <div class="thumb-edges"></div>
                    <img alt="noticia<?php echo $noticia->getImatge(); ?>" src="http://rir.li/<?php echo $noticia->getImatge(); ?>" width="58px" height="62px">
                </div>
            </div>
          <?php } ?>
        <?php } ?>
        <?php if($noticia->getImatge() !=null){ ?>
        <div class="story-item-content group" style="width:97%;">
        <?php }else{ ?>
        <div class="story-item-content group" style="width:100%;">
        <?php } ?>
            <div class="story-item-details">
                <h3 class="story-item-title">
                    <a target="_blank" href="<?php echo $noticia->getUrl(); ?>"><?php echo $noticia->getTitul200(); ?></a>
                </h3>
                <p class="story-item-description">
                    <a class="story-item-source"><?php echo $noticia->getNomDiari();?></a>
                    <a class="story-item-teaser" href="<?php echo $noticia->getUrl(); ?>">
                        <?php echo $noticia->getDescripcio180();?>
                    </a>
                </p>
            </div>
        </div>
</div>

<?php } ?>

<?php if($this->cantitat != null){?>
<script>

    var cantitat = <?php echo $this->cantitat; ?>;

</script>
<?php } ?>
<script>
    //alert(dia);
    var contaremArray = 0;
   // alert(dia);
    //alert(dia.length);
    for(contaremArray=0;contaremArray<dia.length;contaremArray++){

        jQuery("#categoriesMarkers"+dia[contaremArray]).html("<img style=\"vertical-align: -3px;\" src=\""+baseUrl+"/images/checkbox0.png\"/>");
    }
    dia = null;
    dia = Array();
    //alert(dia);
</script>
