<div class="column-container group">
    <div class="columns group">
        <div class="pre-content">
            <div id="left-column" class="column narrow attached-menu  group">
                <ul class="sidebar-menu2">
                        <li><a href="<?php echo $this->baseUrl();?>/index/newsup">Sobre NewsUP</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/contactar">Contactar</a></li>
                        <li><a href="http://blog.newsup.es">Blog</a></li>
                        <li><a class="active" href="<?php echo $this->baseUrl();?>/index/faq">Ayuda &amp; FAQ</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/terminos">Términos de servicio</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/privacidad">Política de privacidad</a></li>
                </ul>
            </div>
            <div id="main-column" class="column attached-menu group" style="border:0px solid #fff;">
                <h1>Ayuda & FAQ</h1>
                 
             <div style="padding-right:8px;">
<br/>Está sección está basada en todas las posibles preguntas más frecuentes que le puedan surgir a los usuarios. Aquí respondemos cada una de éllas.<br/><br/>

<strong>1. ¿Cómo puedo subir una noticia?</strong><br/><br/>

Puede subir una noticia mediante el sistema "Envía su Link" al apartado superior de la web. Está disponible en "Mis Noticias" y en "Noticias Top".<br/><br/>

<strong>2. ¿Puedo subir una noticia de mi blog o página? </strong><br/><br/>

Sí, el sistema "Envía su Link" es totalmente compatible en blogs y en revistas.<br/><br/>

<strong>3. ¿Cómo se colocan las noticias al mapa?</strong><br/><br/>

Haciendo clic en “Colocar en el Mapa” en la noticia.<br/><br/>

<strong>4. ¿Cómo ver todas las noticias colocadas en el Mapa?</strong><br/><br/>

En la sección "El Mapa".<br/><br/>

<strong>5. ¿Puedo cambiar la posición de una noticia en el Mapa?</strong><br/><br/>

Sí. Es posible cambiar la posición de aquellas noticias que no hayan sido colocadas previamente. Y puede hacerlo haciendo clic en "Colocar en el Mapa".<br/><br/>

<strong>6. Hay noticias colocadas en puntos erróneos en el Mapa. ¿Puedo cambiar su posición a su localidad correcta?</strong><br/><br/>

Sólo es posible cambiar la posición del mapa aquellas noticias que sean suyas. Lo que si es posible es recomendar al usuario que subió la noticia que cambie la posición. Esto es posible haciendo clic en "Sugerir Cambio". Está opción enviará automáticamente un mensaje al usuario que subió la noticia sugiriéndole que cambie la posición de la noticia en el Mapa.<br/><br/>

<strong>7. ¿Cómo seguir a un usuario?</strong><br/><br/>

Para poder seguir a un usuario y así poder ver todas sus noticias es posible accediendo en su perfil (hacer clic su nombre de usuario: Enviado por: “nombredeusuario”) y haciendo clic en "Seguirlo".<br/><br/>

<strong>8. ¿Cómo dejar de seguir a un usuario?</strong><br/><br/>

Accediendo a su perfil y haciendo clic "No Seguir".<br/><br/>

<strong>9. ¿Puedo cambiar mi contraseña de acceso de NewsUP?</strong><br/><br/>

Sí. Accediendo a su perfil (Mis Noticias), (Editar Mi Perfil). Y en la sección "Gestionar Perfil" acceder en "Cambiar Contraseña".<br/><br/>

<strong>10. ¿Qué es y cómo funciona el sistema de notificaciones?</strong><br/><br/>

El sistema de notificaciones es un servicio que le informa de todas las novedades en que está relacionado/a (Si alguien le ha comentado su noticia, si un usuario favorito ha subido una noticia,etc). En definitiva, un sistema que le ayudará a que no pierda ni un detalle de todo lo sucedido en NewsUP. <br/><br/>

<strong>11. ¿Es posible cambiar los datos de mi perfil (foto, email, localidad, fecha de nacimiento,...)?</strong><br/><br/>

Sí. Accediendo a su perfil (Mis Noticias), (Editar Mi Perfil).<br/><br/>

<strong>12. No encuentro un diario, revista o blog en la sección "Quiosco". ¿Hay alguna forma para hacer que salga?</strong><br/><br/>

Por ahora, si quiere que salga una revista, un blog o un diario en el "Quiosco" puede contactar con nosotros mediante la sección "Contactar".<br/><br/>

<strong>13. ¿Es posible borrar mi cuenta de NewsUP?</strong><br/><br/>

Para más seguridad no existe ningún sistema automático que permite borrar su cuenta. Pero puede dirigirse a nosotros usando la sección "Contactar" y justificándonos el porque quiere borrar su cuenta.<br/><br/>

<strong>14. ¿Cómo guardar una noticia que me guste?</strong><br/><br/>

Haciendo clic en "Guardar" en la noticia.<br/><br/>

<strong>15. ¿Cómo  puedo buscar un usuario o una noticia?</strong><br/><br/>

Utilizando el buscador localizado en el margen norte-este de la página web.<br/><br/>

<strong>16. Me gustaría saber si alguien de mi lista de correo (Hotmail, Gmail) y/o en Facebook está en NewsUP. ¿Es posible?</strong><br/><br/>

Sí, gracias a la sección "Busca las noticias de sus Amigos". Con esta utilidad podrá saber de todas las personas que tiene agregadas en Hotmail, Gmail y/o Facebook, quiénes están en NewsUP.<br/><br/>

<strong>17. ¿Es posible poner mi propia publicidad en la página web de NewsUP?</strong><br/><br/>

Sí, contactando con nosotros en la sección "Contactar".<br/><br/>

<strong>18. Tengo una pregunta para el equipo de NewsUP. ¿Es posible contactar? </strong><br/><br/>

Sí, en la sección "Contactar".<br/><br/><br/>

Si le quedó alguna duda o tiene alguna otra pregunta que no está en la lista anterior, puede contactar con nosotros usando la sección "Contactar". Estaremos encantados de atenderle.

</div>
        </div>
            <div id="right-column" class="column wide group">
                <?php
                //aqui fem un include
                echo $this->render("rightsidebar.phtml");
                ?>
            </div>
        </div>
</div>
</div>
