<div class="column-container group">
    <div class="columns group">
        <div class="pre-content">
            <div id="left-column" class="column narrow attached-menu  group">
                <ul class="sidebar-menu2">
                        <li><a class="active" href="<?php echo $this->baseUrl();?>/index/newsup">Sobre NewsUP</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/contactar">Contactar</a></li>
                        <li><a href="http://blog.newsup.es">Blog</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/faq">Ayuda &amp; FAQ</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/terminos">Términos de servicio</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/privacidad">Política de privacidad</a></li>
                </ul>
            </div>
            <div id="main-column" class="column attached-menu group" style="border:0px solid #fff;">
                <h1>Sobre NewsUP </h1>
                <div style="margin-top: 20px;">
                    <strong>NewsUP es un proyecto desarrollado por tres jóvenes españoles estudiantes de informática.</strong><br/><br/>
                    Con NewsUP pretendemos dar un <strong>enfoque mejorado en el mundo de la información</strong> ofreciendo la posibilidad a los usuarios de compartir las noticias de <strong>todo el mundo</strong> con el resto de la comunidad.
                    NewsUP pretende mejorar e innovar el sistema de información existente. Así como <strong>reinventar las tecnologías actuales y acercar el flujo de información a la persona. </strong>
                </div>
                <div style="margin-top:20px;font-weight: bold; margin-bottom:10px;">
                    ¿Qué es NewsUP?
                </div>
                <div style="margin-top:5px;">
                    NewsUP es un servicio web de noticias que <strong>permite compartir contenido con carácter informativo con el resto del mundo.</strong>
Gracias a las múltiples utilidades que incorpora NewsUP usted podrá ejercer de periodista compartiendo las noticias que encuentre más relevantes, así como valorar otras noticias, comentarlas, y colocarlas en el mapa.

<br/><br/>Y gracias al servicio de <strong>Quiosco</strong>, nunca más estará desinformado de las noticias más actuales de todos los diarios del mundo. ¡En un sólo clic!

<br/><br/>La utilidad <strong>Mapa</strong> le permitirá colgar todas sus noticias en el mapa terrestre y ver todas las noticias colocadas por toda la comunidad.

<br/>Con el <strong>sistema de notificaciones</strong> estará al día de todo lo que suceda en tus noticias y en tus contactos.

En definitiva, el proyecto NewsUP está en constante desarrollo y crecimiento. En ningún caso es un proyecto cerrado. 
                </div>
                <div style="margin-top:20px;font-weight: bold; margin-bottom:10px;">
                    Desarrolladores de NewsUP
                </div>
                <div style="margin-top:5px;">
NewsUP está formado por un equipo de tres personas:<br/><br/><strong>Pol Alzina Güell</strong> (polalzina@newsup.es)<br/> <strong>Marc Cobos Hernández</strong> (marccobos@newsup.es)<br/>  <strong>Álex Peregrina Cabrera</strong> (alexperegrina@newsup.es)<br/>
                </div>
                <div style="margin-top:20px;font-weight: bold; margin-bottom:10px;">
                    Programación y tecnología utilizada en el desarrollo de NewsUP
                </div>
                <div style="margin-top:5px;">
                    NewsUP ha estado desarrollado desde cero utilizando Zend Framework. Para el desarrollo de NewsUP no se ha utilizado código libre de otras páginas, ni ningún CMS. NewsUP utiliza librerías de Google, MSN y Facebook para poder realizar las búsquedas entre usuarios.
                    Todos los datos con carácter privilegiado y el flujo de éstos se transmiten de forma segura utilizando algoritmos de encriptación.
                </div>
                <div style="margin-top:20px;font-weight: bold; margin-bottom:10px;">
                    La filosofía de NewsUP
                </div>
                <div style="margin-top:5px;">
                    NewsUP se basa en una filosofía de simplicidad y facilidad de uso.

Todas las aplicaciones web y mejoras lanzadas se desarrollan desde el punto de vista de un usuario. Todas y cada una de estas utilidades no requieren un nivel previo de informática.

Toda la web está diseñada y enfocada para todos los públicos.

NewsUP le gusta mejorar día a día: Se ha implementado un sistema de contactar para que todos los usuarios deseados puedan contactar con nosotros, hacer sugerencias, hacer críticas constructivas, opiniones para mejorar la web,...

<strong>Todo es bienvenido.</strong>
                </div>
            </div>
            <div id="right-column" class="column wide group">
                <?php
                //aqui fem un include
                echo $this->render("rightsidebar.phtml");
                ?>
            </div>
        </div>
    </div>
</div>
