<div class="column-container group">
    <div class="columns group">
        <div class="pre-content">
            <div id="left-column" class="column narrow attached-menu  group">
                <ul class="sidebar-menu2">
                        <li><a href="<?php echo $this->baseUrl();?>/index/newsup">Sobre NewsUP</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/contactar">Contactar</a></li>
                        <li><a href="http://blog.newsup.es">Blog</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/faq">Ayuda &amp; FAQ</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/terminos">Términos de servicio</a></li>
                        <li><a class="active" href="<?php echo $this->baseUrl();?>/index/privacidad">Política de privacidad</a></li>
                </ul>
            </div>
            <div id="main-column" class="column attached-menu group" style="border:0px solid #fff;">
                <h1>Política de privacidad</h1>
                <div style="margin-top: 20px;">

<strong>Propiedad intelectual del contenido de la Página – Copyright</strong><br/><br/>

Este sitio de Internet y su contenido son de propiedad de NewsUP. Está prohibida su reproducción total o parcial, su traducción, inclusión, transmisión o almacenamiento sin autorización previa y escrita de NewsUP.<br/><br/>

Es interés de NewsUP la salvaguardia de la privacidad de la información personal del usuario obtenida a través de la página web de la entidad, para lo cual se compromete a adoptar una política de confidencialidad de acuerdo con lo que se establece más adelante.<br/><br/>

Se entiende por información personal aquella suministrada por el usuario para el registro, la cual incluye datos como nombre, identificación, edad, género y correo electrónico. El usuario podrá modificar o actualizar la información suministrada en cualquier momento.<br/><br/>

La información personal proporcionada por el usuario está asegurada por una clave de acceso que sólo él conoce. Por tanto, es el único responsable de mantener en secreto su clave. NewsUP se compromete a no acceder ni pretender conocer dicha clave. Todas las claves son encriptadas y protegidas, para proteger al máximo la confidencialidad del usuario.<br/><br/>

En cumplimiento de la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal, le informamos que sus datos serán incorporados a un fichero con datos de carácter personal denominado "NewsUP DB", cuya finalidad es guardar los datos de registro de los usuarios para futuras acciones de mantenimiento.
Le informamos asimismo que los datos podrán ser comunicados a otras Administraciones públicas en el ámbito de competencias semejantes o materias comunes en cumplimiento de la legislación aplicable. Podrá comunicarnos su oposición a este tratamiento de datos así como ejercer sus derechos de acceso, rectificación y cancelación dirigiéndose al responsable del fichero, "NewsUP", siempre acreditando su identidad en la comunicación conforme a Derecho.

Debido a que ninguna transmisión por Internet es absolutamente segura ni puede garantizarse dicho extremo, el usuario asume el hipotético riesgo que ello implica, el cual acepta y conoce.<br/><br/>

NewsUP no se responsabiliza por cualquier consecuencia derivada por alguna falla técnica en el funcionamiento y/o conservación de datos en el sistema en cualquiera de los apartados de la página web.<br/><br/>

Igualmente, NewsUP no podrá garantizar la disponibilidad de los servicios en línea y de la información que los usuarios requieran en determinado momento. Tampoco incurrirá en responsabilidad con el usuario o terceros, cuando su sitio web no se encuentre disponible.<br/><br/>

Se asume que el usuario conoce y comprende que el servidor se puede actualizar en cualquier momento, lo cual comporta que los servicios de la web de NewsUP no estén disponibles por un período de tiempo.<br/><br/>

NewsUP ha adoptado los niveles de seguridad de protección de los datos personales legalmente requeridos, instalando las medidas técnicas y organizativas necesarias para evitar la pérdida, mal uso, alteración, acceso no autorizado y robo de los datos facilitados.<br/><br/>

NewsUP podrá utilizar cookies durante la prestación de los servicios en la web.<br/><br/>

Se asume que cuando un usuario se registra para hacer uso de los servicios prestados por NewsUP acepta la totalidad de las políticas de privacidad mencionadas.<br/><br/>

                </div>
                
            </div>
            <div id="right-column" class="column wide group">
                <?php
                //aqui fem un include
                echo $this->render("rightsidebar.phtml");
                ?>
            </div>
        </div>
    </div>
</div>
