<div class="column-container group">
    <div class="columns group">
        <div class="pre-content">
            <div id="left-column" class="column narrow attached-menu  group">
                <ul class="sidebar-menu2">
                        <li><a href="<?php echo $this->baseUrl();?>/index/newsup">Sobre NewsUP</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/contactar">Contactar</a></li>
                        <li><a href="http://blog.newsup.es">Blog</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/faq">Ayuda &amp; FAQ</a></li>
                        <li><a class="active" ref="<?php echo $this->baseUrl();?>/index/terminos">Términos de servicio</a></li>
                        <li><a href="<?php echo $this->baseUrl();?>/index/privacidad">Política de privacidad</a></li>
                </ul>
            </div>
            <div id="main-column" class="column attached-menu group" style="border:0px solid #fff;">
                <h1>Términos del Servicio</h1>
                 
             <div style="padding-right:8px;">
<br/>Se presume que cuando un usuario accede al sitio Web de newsup.es lo hace bajo su total responsabilidad y que, por tanto, acepta plenamente y sin reservas el contenido de los términos y condiciones de uso.<br/><br/>

<strong>ACUERDO CON EL USUARIO</strong><br/><br/>

NewsUP se reserva, en todos los sentidos, el derecho de actualizar y modificar en cualquier momento y de cualquier forma, de manera unilateral y sin previo aviso, las presentes condiciones de uso y los contenidos de la página, de modo que le recomendamos revisarlos periódicamente.<br/><br/>

Por otra parte, la prestación del servicio de NewsUP es de carácter libre y gratuito para los usuarios y se rige por los términos y condiciones que se incluyen a continuación, los cuales se entienden como conocidos y aceptados por los/as usuarios/as del sitio:<br/><br/>

<strong>1. DE SUS APORTES</strong><br/><br/>

NewsUP.es, por ser una comunidad interactiva, promueve la participación de los usuarios en diferentes formas. Al navegar por la comunidad y/o participar de manera interactiva en alguno de los espacios contemplados para ello, usted se compromete a no enviar o transmitir contenido alguno que:<br/><br/>

- Usar los contenidos de forma diligente, correcta y lícita.<br/>
- No suprimir, eludir, o manipular el copyright (derechos de autor) y demás datos que identifican los derechos de NewsUP.<br/>
- No emplear los contenidos y, en particular, la información de cualquier otra clase obtenida a través de NewsUP, para emitir publicidad.<br/>
- NewsUP no será responsable por el uso indebido que hagan los usuarios del contenido de su sitio Web.<br/>
- El visitante o usuario del sitio Web se hará responsable por cualquier uso indebido, ilícito o anormal que haga de los contenidos, información o servicios del sitio Web de NewsUP. El visitante o usuario del sitio, directa o por interpuesta persona, no atentará de ninguna manera contra el sitio Web de NewsUP, contra su plataforma tecnológica, contra sus sistemas de información ni tampoco interferirá en su normal funcionamiento.<br/>
- El visitante o el usuario del sitio, no alterará, bloqueará o realizará cualquier otro acto que impida mostrar o acceder a cualquier contenido, información o servicios del sitio Web de NewsUP.<br/>
- El visitante o el usuario del sitio Web de NewsUP, no incurrirá en y desde el mismo, en conductas ilícitas como daños o ataques informáticos, interceptación de comunicaciones, infracciones al derecho de autor, uso no autorizado de terminales, usurpación de identidad, revelación de secretos o falsedad en los documentos.<br/>
- Viole las leyes y tratados de derechos de autor en cualquier territorio.<br/>
- Induzca o invite a actuar de manera ilegal o en si mismo, constituya violaciones a la ley y el orden vigentes.<br/>
- Incite a las personas que tengan acceso a él a involucrarse o a participar en actividades peligrosas, de riesgo, ilegales o que atenten contra su salud física y emocional.<br/>
- Altere el equilibrio psíquico de las personas, las amedrente, atemorice, intimide o cualquier otra alteración.<br/>
- Infrinja las normas legales y/o trasgreda los derechos y libertades de las personas.<br/>
- Sea discriminatorio en cuanto al sexo, religión, raza o cualquier otra violación a los derechos fundamentales y/o las libertades otorgadas y garantizadas por el ordenamiento jurídico.<br/>
- Contenga información falsa o parcial.<br/>
- Incorpore elementos, contenidos, mensajes, formatos, productos y/o servicios ilícitos, violentos, pornográficos o degradantes.<br/>
- Contenga virus u otras características que causen deterioros a otros computadores.<br/>
- Infrinja las normas legales o reglamentarias sobre secreto de las comunicaciones, propiedad intelectual, derecho al honor y a la intimidad personal o familiar.<br/>
- Contenga publicidad, promocione u ofrezca servicios, incluidas sin carácter limitativo las cadenas de dinero, de mensajes, spam (correo no solicitado), etc.<br/>

<br/>En relación con la información descrita anteriormente, NewsUP.es no será en ningún caso responsable por la información aportada por terceros, así como no se responsabilizará de los daños o perjuicios causados por ella.<br/>

<br/>NewsUP.es se reserva el derecho de eliminar del sitio cualquier contenido que no se ajuste a este acuerdo y además podrá, sin previo aviso, suspender y/o borrar todos los usuarios, noticias y/o comentarios que incumplan el presente acuerdo.<br/><br/>

Nota importante: Si algún usuario vulnerara alguna norma descrita anteriormente, por favor, infórmenos lo antes posible para proceder a tomar las acciones que sean necesarias por su cumplimiento.<br/><br/>

<strong>2. DE LOS CONTENIDOS PROPIOS</strong><br/><br/>

NewsUP.es ofrece su contenido como un servicio a sus usuarios, dicho contenido puede ser usado con carácter informativo y/o educativo, o en la forma en que los usuarios deseen. NewsUP.es no se responsabiliza por errores u omisiones que pueda contener dicho material.<br/><br/>

<strong>3. DE LOS CONTENIDOS DE TERCEROS</strong><br/><br/>

Esta página puede tener enlaces a otros sitios de interés o a documentos localizados en otras páginas web de propiedad de otras entidades o personas. Solamente por el hecho de que el usuario acceda a otro sitio web o a un documento individual localizado en otra página, el usuario deberá someterse a las condiciones de uso y a la política de privacidad de la página web a la que acceda.<br/>

<br/>NewsUP.es advierte que al no ser de su titularidad los contenidos del sitio relacionado con las noticias de terceros y/o el posicionamiento de éstas en nuestro mapa terrestre, algunos de estos pueden presentar errores, falsedades, no estar actualizados, etc. De igual manera, no se garantiza el cumplimiento del presente acuerdo por parte de terceros en relación con el contenido, por lo cual NewsUP.es no se responsabilizará por éstos de ninguna manera.<br/><br/>

<strong>4. RESPONSABILIDAD</strong><br/><br/>

NewsUP.es NO SE HACE RESPONSABLE POR LAS INTERPRETACIONES DE SUS CONTENIDOS, NI DEL USO INDEBIDO DE LOS MISMOS Y DE SUS SERVICIOS E INFORMACIÓN, DE IGUAL MANERA NO SE HARÁ RESPONSABLE POR LOS DAÑOS O PERJUICIOS CAUSADOS DE FORMA DIRECTA O INDIRECTA POR O A QUIENES FUERAN ESTIMULADOS A TOMAR DECISIONES O MEDIDAS AL CONSULTAR EL SITIO. LA COMUNIDAD TAMPOCO SE RESPONSABILIZARÁ POR LOS DAÑOS O PERJUICIOS, DIRECTOS, INDIRECTOS, O DE OTRA FORMA, QUE ACARREÉ LA SUSPENSIÓN O TERMINACIÓN DE LOS SERVICIOS, CONTENIDO, O INFORMACIÓN QUE SUMINISTRA A TRAVÉS DEL SITIO WEB. DE NINGUNA MANERA SE HARÁ RESPONSABLE POR LAS CONSECUENCIAS DEL USO INDEBIDO O NEGLIGENTE DE LAS CONTRASEÑAS USADAS PARA ACCEDER AL SITIO.<br/><br/>


El usuario se compromete a defender, desagraviar, reparar, exonerar e indemnizar a NewsUP.es y a todos sus directivos, sus empleados, representantes, agentes, accionistas, miembros, socios, asociados, aliados y abogados, por cualquiera o todos los reclamos, demandas, daños y perjuicios, pérdidas, responsabilidades, costos y gastos (incluyendo cualquier tipo de costo y/o gasto), derivados del uso que realice del sitio web o de cualquier contenido, programa, servicio, información, producto, documento o software disponible en el sitio, o cualquier infracción o violación que realice a este acuerdo, o actos impropios u omisiones que haga.<br/><br/>
             </div>
        </div>
            <div id="right-column" class="column wide group">
                <?php
                //aqui fem un include
                echo $this->render("rightsidebar.phtml");
                ?>
            </div>
        </div>
</div>
</div>
