<div class="column-container group">
    <div class="columns group">
        <div class="pre-content">
            <div id="main-column-user" class="column attached-menu group">
               <div id="titul-categorias" style="padding-left:4px; background:#f2f2f2; border-top:1px solid #e2e2e2; padding:4px 5px 4px 5px;">
                  Perfil de <?php echo $this->userfora->getUsername(); ?>
               </div>
                <div class="profile-title group">
                    <div style="float:left;">
                        <?php if($this->userfora->getImage() !=null){ ?>
                        <?php
                            $nomImatge = $this->userfora->getImage();
                            $img = "img/$nomImatge";
                            //Zend_Debug::dump($img);

                            list($amplada, $alt, $tipus, $atributs) = getimagesize($img);
                            if($amplada>$alt){
                                $ampladaNova = 150;
                                $altNou = floor($alt * $ampladaNova / $amplada);
                            }else{
                                $altNou = 130;
                                $ampladaNova = floor($amplada * $altNou / $alt);
                            }


                        ?>
                        <a style="width:<?php echo $ampladaNova; ?>px; height:<?php echo $altNou ?>px;" class="current-user-thumbnail">
                            <img alt="usuari" src="<?php echo $this->baseUrl();?>/img/<?php echo $this->userfora->getImage(); ?>" width="<?php echo $ampladaNova; ?>px" height="<?php echo $altNou ?>px">
                        </a>
                        <?php }else{ ?>
                        <a style="background: url(images/perfil2.png) no-repeat center #E5ECF3;
                           width:100px; height:120px;" class="current-user-thumbnail"></a>
                        <?php }?>
                    </div>
                    <?php if($this->loggedIn==true){ ?>
                    <?php if($this->user->id_user != $this->userfora->getId()){ ?>
                    <div style="float:left; padding-left: 20px; padding-top:16px; width: 56%;">
                        <div style="float:left">
                            <span style="font-weight:bold; font-size: 1em;">Nombre de usuario:</span>
                            <span style="padding-left:10px;"><?php echo $this->userfora->getUsername(); ?></span>
                        </div>
                         <div style="float:left; padding-left: 35px;">
                             <span style="font-weight:bold; font-size: 1em;">Localidad:</span>
                             <span style="padding-left:10px;">
                               <?php if($this->dadesSeguit->Localidad!=null){ ?>
                                <?php echo $this->dadesSeguit->Localidad; ?>
                               <?php }else{ ?>
                                No especificado
                               <?php } ?>
                             </span>
                         </div>
                        <div style="clear:both; padding-top:15px;">
                             <span style="font-weight:bold; font-size: 1em;">Su vida:</span>
                             <span style="padding-left:10px;">
                               <?php if($this->dadesSeguit->Tuvida!=null){ ?>
                                <?php echo $this->dadesSeguit->Tuvida; ?>
                               <?php }else{ ?>
                                 No especificado
                               <?php } ?>
                             </span>
                         </div>
                         <div style="clear:both; padding-top:15px;">
                             <span style="font-weight:bold; font-size: 1em;">Página web:</span>
                             <span style="padding-left:10px;">
                               <?php if($this->dadesSeguit->Aficiones!=null){ ?>
                                <?php echo $this->dadesSeguit->Aficiones; ?>
                               <?php }else{ ?>
                                 No especificado
                               <?php } ?>
                             </span>
                          </div>
                         <div style="clear:both; padding-top:15px;">
                             <span style="font-weight:bold; font-size: 1em;">Fecha nacimiento:</span>
                             <span style="padding-left:10px;">
                               <?php if($this->dadesSeguit->Data_neixament!=null){ ?>
                                <?php $data = explode("-",$this->dadesSeguit->Data_neixament); ?>
                                <?php echo $data[2]."-".$data[1]."-".$data[0]; ?>
                               <?php }else{ ?>
                                 No especificado
                               <?php } ?>
                             </span>
                          </div>
                    </div>

                    <?php $segueixo = false; ?>
                    <?php if($this->loggedIn==true){ ?>
                    <?php foreach($this->seguiments as $seguiment){ ?>
                        <?php if($seguiment == $this->userfora->getId()){ ?>
                        <?php  $segueixo = true;?>
                        <?php }?>
                    <?php } ?>
                    <?php } ?>
                    <?php if($segueixo == true){ ?>
                    <div style="float:left; padding-left:10px; padding-top: 16px;" id="seguidornou<?php echo $this->userfora->getId(); ?>">
                          <span style="height: 15px; text-align:center; width: 125px;" id="seguidorDown" class="btn btn-special4 has-tooltip" rel="<?php echo $this->userfora->getId(); ?>">
                             No Seguir<span class="puntuarNew comment-bury"></span>
                          </span>
                    </div>
                    <?php }else{ ?>
                    <div style="float:left; padding-left:10px; padding-top: 16px;" id="seguidornou<?php echo $this->userfora->getId(); ?>">
                        <span style="height: 15px; text-align:center; width: 125px;" id="seguidorOk" class="btn btn-follow btn-primary has-tooltip" rel="<?php echo $this->userfora->getId(); ?>">Seguirlo<span class="puntuarNew comment-digg" ></span></span>
                    </div>
                    <?php } ?>
                    <?php }else{ ?>
                    <div style="float:left; padding-left: 20px; padding-top:16px; width: 76%;">
                        <div style="float:left">
                            <span style="font-weight:bold; font-size: 1em;">Nombre de usuario:</span>
                            <span style="padding-left:10px;"><?php echo $this->userfora->getUsername(); ?></span>
                        </div>
                          <div style="float:left; padding-left: 35px;">
                             <span style="font-weight:bold; font-size: 1em;">Localidad:</span>
                             <span style="padding-left:10px;">
                               <?php if($this->dadesSeguit->Localidad!=null){ ?>
                                <?php echo $this->dadesSeguit->Localidad; ?>
                               <?php }else{ ?>
                                No especificado
                               <?php } ?>
                             </span>
                         </div>
                        <div style="clear:both; padding-top:15px;">
                             <span style="font-weight:bold; font-size: 1em;">Su vida:</span>
                             <span style="padding-left:10px;">
                               <?php if($this->dadesSeguit->Tuvida!=null){ ?>
                                <?php echo $this->dadesSeguit->Tuvida; ?>
                               <?php }else{ ?>
                                 No especificado
                               <?php } ?>
                             </span>
                         </div>
                         <div style="clear:both; padding-top:15px;">
                             <span style="font-weight:bold; font-size: 1em;">Página web:</span>
                             <span style="padding-left:10px;">
                               <?php if($this->dadesSeguit->Aficiones!=null){ ?>
                                <?php echo $this->dadesSeguit->Aficiones; ?>
                               <?php }else{ ?>
                                 No especificado
                               <?php } ?>
                             </span>
                          </div>
                            <div style="clear:both; padding-top:15px;">
                                 <span style="font-weight:bold; font-size: 1em;">Fecha nacimiento:</span>
                                 <span style="padding-left:10px;">
                                   <?php if($this->dadesSeguit->Data_neixament!=null){ ?>
                                    <?php $data = explode("-",$this->dadesSeguit->Data_neixament); ?>
                                    <?php echo $data[2]."-".$data[1]."-".$data[0]; ?>
                                   <?php }else{ ?>
                                     No especificado
                                   <?php } ?>
                                 </span>
                              </div>
                    </div>
                    <?php } ?>
                    <?php }else{ ?>
                     <div style="float:left; padding-left: 20px; padding-top:16px; width: 76%;">
                        <div style="float:left">
                            <span style="font-weight:bold; font-size: 1em;">Nombre de usuario:</span>
                            <span style="padding-left:10px;"><?php echo $this->userfora->getUsername(); ?></span>
                        </div>
                          <div style="float:left; padding-left: 35px;">
                             <span style="font-weight:bold; font-size: 1em;">Localidad:</span>
                             <span style="padding-left:10px;">
                               <?php if($this->dadesSeguit->Localidad!=null){ ?>
                                <?php echo $this->dadesSeguit->Localidad; ?>
                               <?php }else{ ?>
                                No especificado
                               <?php } ?>
                             </span>
                         </div>
                        <div style="clear:both; padding-top:15px;">
                             <span style="font-weight:bold; font-size: 1em;">Su vida:</span>
                             <span style="padding-left:10px;">
                               <?php if($this->dadesSeguit->Tuvida!=null){ ?>
                                <?php echo $this->dadesSeguit->Tuvida; ?>
                               <?php }else{ ?>
                                 No especificado
                               <?php } ?>
                             </span>
                         </div>
                         <div style="clear:both; padding-top:15px;">
                             <span style="font-weight:bold; font-size: 1em;">Página web:</span>
                             <span style="padding-left:10px;">
                               <?php if($this->dadesSeguit->Aficiones!=null){ ?>
                                <?php echo $this->dadesSeguit->Aficiones; ?>
                               <?php }else{ ?>
                                 No especificado
                               <?php } ?>
                             </span>
                          </div>
                            <div style="clear:both; padding-top:15px;">
                                 <span style="font-weight:bold; font-size: 1em;">Fecha nacimiento:</span>
                                 <span style="padding-left:10px;">
                                   <?php if($this->dadesSeguit->Data_neixament!=null){ ?>
                                    <?php $data = explode("-",$this->dadesSeguit->Data_neixament); ?>
                                    <?php echo $data[2]."-".$data[1]."-".$data[0]; ?>
                                   <?php }else{ ?>
                                     No especificado
                                   <?php } ?>
                                 </span>
                              </div>
                    </div>
                    <?php }?>
                </div>
                <ul id="comment-sorting" class="pillboxes filter-menu group" style="margin-top: 10px; margin-bottom: 10px; background: #eee;">
                    <li>
                        <a id="filter-noticias" class="sort  active" rel="<?php echo $this->userfora->getId(); ?>">Sus noticias <span style="font-weight:bold; color:#fff; margin-left: 10px; background:#669900; -moz-border-radius:25px; -webkit-border-radius:25px; border-radius:25px;">&nbsp;&nbsp;&nbsp;<?php echo $this->cantitat; ?>&nbsp;&nbsp;&nbsp;</span></a>
                    </li>
                    <li class="divider show-expanded">
                        <a id="filter-lesiguen" class="sort" rel="<?php echo $this->userfora->getId(); ?>">Le siguen <span style="font-weight:bold; color:#fff; margin-left: 10px; background:#669900; -moz-border-radius:25px; -webkit-border-radius:25px; border-radius:25px;" id="segueixenAra">&nbsp;&nbsp;&nbsp;<?php echo $this->segueixen; ?>&nbsp;&nbsp;&nbsp;</span></a>
                    </li>
                    <li class="divider show-expanded">
                        <a id="filter-sigue" class="sort" rel="<?php echo $this->userfora->getId(); ?>">Él sigue <span style="font-weight:bold; color:#fff; margin-left: 10px; background:#669900; -moz-border-radius:25px; -webkit-border-radius:25px; border-radius:25px;">&nbsp;&nbsp;&nbsp;<?php echo $this->segueix; ?>&nbsp;&nbsp;&nbsp;</span></a>
                    </li>
                </ul>
                <div id="aquiNews">
                    <?php if($this->noticiesFinals == null){ ?>
                        <div class="nothing-found topbar-spacer">
                            <p class="title">Este usuario aún no ha subido ninguna noticia.</p>
                        </div>
                    <?php }else{ ?>
                    <?php
                    //aqui fem un include
                    echo $this->render("foreachnoticiesuser.phtml"); ?>
                    <?php } ?>
                    <?php if($this->cantitat >15){ ?>
                      <script>

                        var cantitat = <?php echo $this->cantitat; ?>;

                      </script>
                        <ul class="pagination group btn-loader btn-loader-bottom no-prev no-next story-list-container" role="navigation"aria-labelledby="paginglabel">
                            <li class="prev" >
                                <a class="btn btn-default btn-small" id="prev-out" rel="<?php echo $this->pagina; ?>" idus="<?php echo $this->userfora->getId(); ?>">
                                    <span class="uitext" id="prev">Anterior</span>
                                </a>
                            </li>
                            <li class="page-num" style="padding-top:7px;">
                                Página
                                <span class="pagination-current"><?php echo $this->pagina; ?></span>
                            </li>
                            <li class="next">
                                <a class="btn btn-default btn-small" id="next-out" rel="<?php echo $this->pagina; ?>" idus="<?php echo $this->userfora->getId(); ?>">
                                    <span class="uitext" id="next">Siguiente</span>
                                </a>
                            </li>
                        </ul>
                     <?php } ?>
                </div>
              
            </div>
             <div id="right-column" class="column wide group">
                <?php
                //aqui fem un include
                echo $this->render("rightsidebar.phtml");
                ?>
              </div>
        </div>
    </div>
</div>
<script>
    var paginaSegueixen = false;
    
    segueixen2 = <?php echo $this->segueixen; ?>;
    <?php if($this->usuario != null){ ?>
    idActual = <?php echo $this->usuario->getId()?>;
    <?php } ?>
  
    jQuery("span#seguidorOk").live("click",function(){
        
        id = jQuery(this).attr("rel");

        if(loggedIn==false){
            jQuery("div#no-login-dock-punts").fadeIn(300);
            x=1;

        }

        if(x==0){
            x = 1;
            jQuery.ajax({
                    type: "POST",
                    url: baseUrl+"/privat/seguidorok",
                    async: true,
                    data: "&id="+id,

                    success: function(data){
                        if(data){
                           jQuery("div#seguidornou"+id).html(data);
                           segueixen2++

                           jQuery("span#segueixenAra").html("&nbsp;&nbsp;&nbsp;"+segueixen2+"&nbsp;&nbsp;&nbsp;");
                           if(paginaSegueixen==true){
                               Seguidors(id);
                           }

                           x=0;
                        }
                    }
                })
        }
    });

    function Seguidors(id){

            jQuery.ajax({
                        type: "POST",
                        url: baseUrl+"/index/lesiguen",
                        async: true,
                        data: "&id="+id,

                        success: function(data){
                            if(data){
                               
                               jQuery("div#aquiNews").fadeOut(0);
                               jQuery("div#aquiNews").html(data);
                               jQuery("div#aquiNews").slideDown(320);
                               jQuery("div#aquiNews").fadeIn(0);
                               
                               jQuery("a#filter-lesiguen").addClass("active");
                               jQuery("a#filter-noticias").removeClass("active");
                               jQuery("a#filter-sigue").removeClass("active");
                            }
                        }
            })
    }

     jQuery("span#seguidorDown").live("click",function(){
        id = jQuery(this).attr("rel");
       
        if(loggedIn==false){
            jQuery("div#no-login-dock-punts").fadeIn(300);
            y=1;

        }

        if(y==0){
            y=1;
            jQuery.ajax({
                    type: "POST",
                    url: baseUrl+"/privat/seguidordown",
                    async: true,
                    data: "&id="+id,

                    success: function(data){
                        if(data){
                           jQuery("div#seguidornou"+id).html(data);
                           segueixen2--;
                           jQuery("div#usuarioPetit"+idActual).slideUp(420);
                           jQuery("div#usuarioPetit"+idActual).fadeOut();
                           jQuery("span#segueixenAra").html("&nbsp;&nbsp;&nbsp;"+segueixen2+"&nbsp;&nbsp;&nbsp;");
                            y=0;
                        }
                    }
                })
        }
    });

    jQuery("a#filter-lesiguen").live("click",function(){

        id = jQuery(this).attr("rel");

            jQuery.ajax({
                        type: "POST",
                        url: baseUrl+"/index/lesiguen",
                        async: true,
                        data: "&id="+id,

                        success: function(data){
                            if(data){
                               jQuery("div#aquiNews").html(data);
                               jQuery("a#filter-lesiguen").addClass("active");
                               jQuery("a#filter-noticias").removeClass("active");
                               jQuery("a#filter-sigue").removeClass("active");
                            }
                        }
            })

     });

         jQuery("a#filter-sigue").live("click",function(){

        id = jQuery(this).attr("rel");

            jQuery.ajax({
                        type: "POST",
                        url: baseUrl+"/index/sigue",
                        async: true,
                        data: "&id="+id,

                        success: function(data){
                            if(data){
                               jQuery("div#aquiNews").html(data);
                               jQuery("a#filter-lesiguen").removeClass("active");
                               jQuery("a#filter-noticias").removeClass("active");
                               jQuery("a#filter-sigue").addClass("active");
                            }
                        }
            })

     });

         jQuery("a#filter-noticias").live("click",function(){

        id = jQuery(this).attr("rel");

            jQuery.ajax({
                        type: "POST",
                        url: baseUrl+"/index/noticiasseguidor",
                        async: true,
                        data: "&id="+id,

                        success: function(data){
                            if(data){
                               jQuery("div#aquiNews").html(data);
                               jQuery("a#filter-lesiguen").removeClass("active");
                               jQuery("a#filter-noticias").addClass("active");
                               jQuery("a#filter-sigue").removeClass("active");
                            }
                        }
            })

     });




</script>
