<?php if($this->adminSi == true){ ?>
     <?php echo $this->render("adminTool.phtml"); ?>
<?php }else if($this->adminSi2 == true){ ?>
     <?php echo $this->render("adminTool2.phtml"); ?>
<?php }else if($this->mapaSi == true){ ?>
    <?php echo $this->render("map.phtml"); ?>
<?php }else if($this->mapaSi2 == true){ ?>
    <?php echo $this->render("map_new.phtml"); ?>
<?php }else if($this->mapaSi3 == true){ ?>
    <?php echo $this->render("map_ver.phtml"); ?>
<?php }else if($this->mapaSi4 == true){ ?>
    <?php echo $this->render("map_cambiar.phtml"); ?>
<?php }else{ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="es">

<head>
        <meta http-equiv="X-UA-Compatible" content="IE=9"/>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="pragma" content="no-cache" />
        <meta http-equiv="expires" content="-1" />
        <meta name="geo.region" content="ES-CT" />
        <meta name="geo.placename" content="Manresa" />
        <meta name="geo.position" content="41.725175;1.823353" />
        <meta name="ICBM" content="41.725175, 1.823353" />
        <meta name="google-site-verification" content="eIjNlTuTuh5q3R2zJySCRrfq5y5BfESW-1A4JkoNXmw" />
        <?php if($this->metadescripcio == null){ ?>
        <meta name="Description" content="NewsUP es un servicio web de noticias que permite compartir contenido con carácter informativo con el resto del mundo." />
        <?php }else{ ?>
        <meta name="Description" content="<?php echo $this->metadescripcio; ?>" />
        <?php } ?>

        <?php if($this->metanom == null){ ?>
        <title>NewsUp Noticias</title>
        <?php }else{ ?>
        <title><?php echo $this->metanom; ?> - NewsUp</title>
        <?php } ?>
        <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-21991981-1']);
          _gaq.push(['_setDomainName', '.newsup.es']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>

    <!-- Meta Images -->
         <base href="http://<?php echo $this->escape($_SERVER['HTTP_HOST']) . $this->escape($this->baseUrl()); ?>/" />

	 <link rel="shortcut icon" href="<?php echo $this->baseUrl();?>/images/favicon.ico" type="image/x-icon" />

         <!-- Stylesheets -->
        <link  rel="stylesheet" type="text/css"  href="<?php echo $this->baseUrl();?>/css/styleSearch.css"/>
        <link  rel="stylesheet" type="text/css"  href="<?php echo $this->baseUrl();?>/css/style2.css"/>
        <link  rel="stylesheet" type="text/css"  href="<?php echo $this->baseUrl();?>/css/style.css"/>
        <link  rel="stylesheet" type="text/css"  href="<?php echo $this->baseUrl();?>/css/style3.css"/>
        <link  rel="stylesheet" type="text/css"  href="<?php echo $this->baseUrl();?>/css/jquery-ui-1.7.2.custom.css"/>
        <link  rel="stylesheet" type="text/css"  href="<?php echo $this->baseUrl();?>/css/jquery.fileupload-ui.css" />
         
         
         <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.min.js"></script>
         <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery-ui.min.js"></script>

         <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.fileupload.js"></script>
         <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.fileupload-ui.js"></script>
         <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery-ui-1.7.2.custom.min.js"></script>
        <!-- <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery-1.3.2.min.js"></script>
-->
         <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/funcionsTempsNext.js"></script>
         <script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/javaSha1.js"></script>


         



         <script type="text/javascript">
             var baseUrl = "<?php echo $this->baseUrl() ?>";
             var loggedIn = false;
         </script>
</head>
<body style="min-width:992px;">
    <div id="preloadImagesBody"></div>
    <div id="imatgeNewsup"><img src="<?php echo $this->baseUrl();?>/images/newsupgran.jpg" alt="newsup"/></div>
    
    <?php if($this->loggedIn==true){ ?>
    <script type="text/javascript">
        loggedIn= true;
    </script>
    <?php } ?>
    <?php echo $this->render("missatjes.phtml"); ?>
    <div class="header-wrapper">
    <div class="header group">
        <a id="header-logo" class="sprite1 newsup-logo" href="<?php echo $this->baseUrl();?>">NewsUP</a>
        <ul class="main-navigation tabbed-navigation group">
            <?php if($this->loggedIn==true): ?>
            <li>
                <a id="header-mynews" <?php if($this->mostra == "1") { echo "class='active'"; } ?> href="<?php echo $this->baseUrl(); ?>/privat"><span class="elbow-left"></span><span class="elbow-right"></span>Mis Noticias</a>
            </li>
            <?php endif ?>
            <li>
                <a id="header-topnews" <?php if($this->mostra == "2") { echo "class='active'"; } ?> href="<?php echo $this->baseUrl(); ?>"><span class="elbow-left"></span><span class="elbow-right"></span>Noticias Top</a>
            </li>
            <li>
                <a id="header-upcoming"  <?php if($this->mostra == "3") { echo "class='active'"; } ?>href="<?php echo $this->baseUrl(); ?>/map"><span class="elbow-left"></span><span class="elbow-right"></span>El Mapa</a>
            </li>
            <li>
                <a id="header-upcoming"  <?php if($this->mostra == "5") { echo "class='active'"; } ?>href="<?php echo $this->baseUrl(); ?>/quiosco"><span class="elbow-left"></span><span class="elbow-right"></span>Quiosco</a>
            </li>
        </ul>
    <?php if($this->loggedIn==true): ?>
    <div class="float-right-login group">
    <?php else: ?>
    <div class="float-right group">
    <?php endif ?>
        <?php echo $this->render("login.phtml"); ?>
        
        <form id="header-search-form" class="header-search" method="get" action="<?php echo $this->baseUrl(); ?>/search">
            <input type="text" value="Buscar usuarios y noticias" id="q" name="buscador"/>
            <input type="submit" value="" id="search-button" name="submit"/>
        </form>
    </div>
    </div>
    </div>
    <div class="page-wrapper group ">
        <!--El centre de la pagina el contingut, lo blanc-->
         <?php echo $this->layout()->content ?>
    </div>
    <div class="footer">
        <?php echo $this->render("footer.phtml"); ?>
    </div>

 

</body>

</html>
<?php } ?>
