<ul class="group">
    <li>&copy; NewsUP 2011</li>
    <li><a href="<?php echo $this->baseUrl();?>/index/newsup">Sobre NewsUP</a></li>
    <li><a href="<?php echo $this->baseUrl();?>/index/contactar">Contactar</a></li>
    <li><a href="http://blog.newsup.es">Blog</a></li>
    <li><a href="<?php echo $this->baseUrl();?>/index/faq">Ayuda &amp; FAQ</a></li>
    <li><a href="<?php echo $this->baseUrl();?>/index/terminos">Términos de servicio</a></li>
    <li><a href="<?php echo $this->baseUrl();?>/index/privacidad">Política de privacidad</a></li>
</ul>