<?php $cont=0; ?>
<?php if($this->feedDiaris == null){ ?>
        <div  class="story-item-gutters group" style="margin-top: 17px; margin-bottom: 14px;">
            <div style="padding:5px;font-weight: bold;text-align: center;">No hay medios con estas características<br/></div>
        </div>
<?php }else{ ?>
    <?php foreach($this->feedDiaris as $diari){ ?>
        <?php if($cont==0){ ?>
            <div style="clear:both;" class="diari-tic" >
              <div class="checkbox-marker-cat" id="categoriesMarkers<?php echo $diari->getId(); ?>" rel="<?php echo $diari->getId(); ?>"><img style="vertical-align: -3px;" src="<?php echo $this->baseUrl(); ?>/images/checkbox0.png"/></div>
              <div class="checkbox-marker-cat2" rel="<?php echo $diari->getId(); ?>"><img style="vertical-align: -3px; padding-left: 10px;" src="<?php echo $this->baseUrl(); ?>/favicons/<?php echo $diari->getFavicon(); ?>" width="16px" height="16px"/></div>
              <span style="padding-left:15px;padding-top:3px;"><?php echo $diari->getNom(); ?></span>
            </div>
        <?php }else{ ?>
           <div class="diari-tic">
              <div class="checkbox-marker-cat" id="categoriesMarkers<?php echo $diari->getId(); ?>" rel="<?php echo $diari->getId(); ?>"><img style="vertical-align: -3px;" src="<?php echo $this->baseUrl(); ?>/images/checkbox0.png"/></div>
              <div class="checkbox-marker-cat2" rel="<?php echo $diari->getId(); ?>"><img style="vertical-align: -3px; padding-left: 10px;" src="<?php echo $this->baseUrl(); ?>/favicons/<?php echo $diari->getFavicon(); ?>" width="16px" height="16px"/></div>
              <span style="padding-left:15px;padding-top:3px;"><?php echo $diari->getNom(); ?></span>
            </div>
        <?php } ?>
        <?php $cont++ ?>
    <?php } ?>
<?php } ?>

<script>
    var contaremArray = 0;
   // alert(dia);
    //alert(dia.length);
    for(contaremArray=0;contaremArray<dia.length;contaremArray++){
        
        jQuery("#categoriesMarkers"+dia[contaremArray]).html("<img style=\"vertical-align: -3px;\" src=\""+baseUrl+"/images/checkbox1.png\"/>");
    }


</script>